server {
    # Bind Nginx to port 4409 internally.
    listen       4409;
    listen  [::]:4409;
    server_name  localhost;

    # Static build target location.
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Redirect server errors to the static page /50x.html
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}